add config-dir with suitable XDG default
Signed-off-by: Christopher Hall <hsw@bitmark.com>

diff --git a/bin/bitmark-pay b/bin/bitmark-pay
--- a/bin/bitmark-pay
+++ b/bin/bitmark-pay
@@ -14,6 +14,7 @@ USAGE()
   echo '       --help           -h         this message'
   echo '       --verbose        -v         more messages'
   echo '       --network=NET    -n NET     set the network ['"${network}"']'
+  echo '       --config-dir=DIR -c DIR     set the config directory ['"${config_dir}"']'
   echo '       --debug          -d         show debug information'
   exit 1
 }
@@ -54,10 +55,17 @@ network=testing
 java_options=
 json=
 application=%%BITMARK_PAY_JAR%%
+config_dir=
+
+if [ -n "${XDG_CONFIG_HOME}" -a -d "${XDG_CONFIG_HOME}" ]
+then
+  config_dir="${XDG_CONFIG_HOME}/bitmark-pay"
+  mkdir -p -m 0700 "${config_dir}"
+fi
 
 getopt=/usr/local/bin/getopt
 [ -x "${getopt}" ] || getopt=getopt
-args=$(${getopt} -o hvn:jd --long=help,verbose,network:,json,debug -- "$@") ||exit 1
+args=$(${getopt} -o hvn:c:jd --long=help,verbose,network:,config-dir:,json,debug -- "$@") ||exit 1
 
 # replace the arguments with the parsed values
 eval set -- "${args}"
@@ -74,6 +82,13 @@ do
       shift
       ;;
 
+    (-c|--config-dir)
+      config_dir="$2"
+      [ -z "${config_dir}" ] || USAGE "empty --config-dir option"
+      [ -d "${config_dir}" ] || USAGE "directory does not exist for: --config-dir=$2"
+      shift
+      ;;
+
     (-j|--json)
       json='--json'
       ;;
@@ -87,8 +102,12 @@ do
       break
       ;;
 
+    (-h|--help)
+      USAGE
+      ;;
+
     (*)
-      USAGE invalid argument $1
+      USAGE "invalid argument: $1"
       ;;
   esac
   shift
@@ -96,8 +115,8 @@ done
 
 [ X"${debug}" = X"yes" ] && set -x
 
-config_dir="bitmark-pay"
-[ -d "${config_dir}" ] || ERROR "missing configuration: ${config_dir}"
+[ -z "${config_dir}" ] && ERROR "configuration directory cannot be blank"
+[ -d "${config_dir}" ] || ERROR "missing configuration directory: ${config_dir}"
 
 # no arguments, just display info
 if [ $# -eq 0 ]
